on:
  push:
    branches: 
      - master








jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'testing githup action'
        run: pwd
     
      - name: 'testing printing'
        run: echo Dina
      - name: 'printing folder contents before'
        run: ls
   
   
   
      - uses: actions/checkout@v3
      - name: 'after'
        run: ls 
   
      - name: "login to docker hub"  
        run: docker login --username  ${{ secrets.DOCKER_USERNAME }} --password  ${{ secrets.DOCKER_LOGIN }}
      - name: "building image"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myimage .

      - name: "pushing to docker hub"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myimage 